### ISSUE TITLE
Add server side crash reporting via heroku .. maybe honey badger

### ISSUE THREAD

**Issue by samccone** [mojotech/sass2stylus#23]

**Comment by damionjn** [comment]
I've written a bash script to replace all of the scss with stylus for an Ionic project I'm working on which uses the API, but the server's been down all weekend and I'm unable to finish error checking. Any updates on this?

**Comment by paulcpederson** [comment]
@damionjn I turned this into a gem which you could use until they get the server back up: https://github.com/paulcpederson/sass2stylus

**Comment by samccone** [comment]
just kicked the sever!

all up and running! thanks for the issue guys.
